// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjkbrdYSp7eahSUzh0UKyh20EF4ugJryY',
    appId: '1:934524080089:web:3ba32328f5752f2a0ed3c8',
    messagingSenderId: '934524080089',
    projectId: 'vpn-project-dd7db',
    authDomain: 'vpn-project-dd7db.firebaseapp.com',
    storageBucket: 'vpn-project-dd7db.firebasestorage.app',
    measurementId: 'G-08N0QHPCY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe3x-QnqxmDTAZPFQ8imd813KwiMceNNo',
    appId: '1:934524080089:android:249b32233481ea2d0ed3c8',
    messagingSenderId: '934524080089',
    projectId: 'vpn-project-dd7db',
    storageBucket: 'vpn-project-dd7db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKrKl_fBAfkIkRMsT2OFu2jRfljNdQfU0',
    appId: '1:934524080089:ios:8221b33e963506f40ed3c8',
    messagingSenderId: '934524080089',
    projectId: 'vpn-project-dd7db',
    storageBucket: 'vpn-project-dd7db.firebasestorage.app',
    iosBundleId: 'com.example.vpn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKrKl_fBAfkIkRMsT2OFu2jRfljNdQfU0',
    appId: '1:934524080089:ios:8221b33e963506f40ed3c8',
    messagingSenderId: '934524080089',
    projectId: 'vpn-project-dd7db',
    storageBucket: 'vpn-project-dd7db.firebasestorage.app',
    iosBundleId: 'com.example.vpn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjkbrdYSp7eahSUzh0UKyh20EF4ugJryY',
    appId: '1:934524080089:web:3e17eca532d47ea70ed3c8',
    messagingSenderId: '934524080089',
    projectId: 'vpn-project-dd7db',
    authDomain: 'vpn-project-dd7db.firebaseapp.com',
    storageBucket: 'vpn-project-dd7db.firebasestorage.app',
    measurementId: 'G-MLM4K7KW73',
  );
}
